[package]
name = "oprf_nullifier"
type = "bin"
authors = ["Aditya Bisht"]

[dependencies]
noir_bigcurve = { tag = "v0.6.0", git = "https://github.com/noir-lang/noir_bigcurve" }
bignum = {tag = "v0.5.4", git = "https://github.com/noir-lang/noir-bignum"}