salt = ""
user_id = ""
user_id_commitment = ""

[chaum_pedersen_proof.c]
base4_slices = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
skew = ""

[chaum_pedersen_proof.s]
base4_slices = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
skew = ""

[nullifier]
is_infinity = ""

[nullifier.x]
limbs = ["", "", ""]

[nullifier.y]
limbs = ["", "", ""]

[oprf_response]
is_infinity = ""

[oprf_response.x]
limbs = ["", "", ""]

[oprf_response.y]
limbs = ["", "", ""]

[r]
base4_slices = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
skew = ""
