nullifier = ""
salt = ""
user_id = ""
user_id_commitment = ""

[chaum_pedersen_proof.c]
limbs = ["", "", ""]

[chaum_pedersen_proof.s]
limbs = ["", "", ""]

[oprf_pubkey]
is_infinity = ""

[oprf_pubkey.x]
limbs = ["", "", ""]

[oprf_pubkey.y]
limbs = ["", "", ""]

[oprf_response]
is_infinity = ""

[oprf_response.x]
limbs = ["", "", ""]

[oprf_response.y]
limbs = ["", "", ""]

[r]
limbs = ["", "", ""]
