[package]
name = "mpc"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ed-on-bn254 = "0.4.0"
ark-std = "0.4.0"
rand = "0.8"
once_cell = "1.19"
thiserror = "2.0.12"
anyhow = "1.0.97"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
ark-serialize = "0.4.0"
actix-web = "4.10.2"
ark-ec = "0.4.0"
num-bigint = { version = "0.4.6", features = ["serde", "rand"] }
