[package]
name = "mpc"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
once_cell = "1.19"
thiserror = "2.0.12"
anyhow = "1.0.97"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
actix-web = "4.10.2"
k256 = { version = "0.13.4", features = ["serde"] }
num-bigint = { version = "0.4.6", features = ["serde", "rand"] }
num-traits = "0.2"
hex = "0.4"
sha2 = "0.10.8"
uuid = { version = "1.16.0", features = ["v4"] }
clap = { version = "4.5.1", features = ["derive"] }
alloy = { version = "0.12", features = ["full"] }
tokio = { version = "1.35.1", features = ["full"] }
dotenv = "0.15.0"
