name: Forge Tests

on:
  push:
    branches: main
    paths:
      - 'packages/registry/**'
  pull_request:
    branches: main
    paths:
      - 'packages/registry/**'
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  forge-tests:
    name: Foundry project
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/registry
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
